name: Build & Deploy (Azure Container)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      repo_slug: ${{ steps.prep.outputs.repo_slug }}
      image_sha: ${{ steps.prep.outputs.image_sha }}
    steps:
      - uses: actions/checkout@v4

      - id: prep
        run: |
          echo "repo_slug=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}/discord-voice-bot:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "image_sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker build -t "$IMAGE" .

      - name: Push
        run: docker push "$IMAGE"

      - name: Tag & push latest
        run: |
          docker tag "$IMAGE" ghcr.io/${{ steps.prep.outputs.repo_slug }}/discord-voice-bot:latest
          docker push ghcr.io/${{ steps.prep.outputs.repo_slug }}/discord-voice-bot:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v3
        with:
          app-name: bot-online-vc
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/${{ needs.build-and-push.outputs.repo_slug }}/discord-voice-bot:${{ needs.build-and-push.outputs.image_sha }}
